export const catalog = [
  { title: "Latest Dramas", filter: "" },
  { title: "Korean Drama", filter: "/category/korean-drama" },
  { title: "Chinese Drama", filter: "/category/chinese-drama" },
  { title: "English Dubbed", filter: "/category/english-dubbed" },
  { title: "Hindi Dubbed", filter: "/category/hindi-dubbed" },
  { title: "Japanese Drama", filter: "/category/japanese-drama" },
  { title: "Movies", filter: "/category/movie" },
];

export const genres = [
  { title: "Action", filter: "/category/action" },
  { title: "Adventure", filter: "/category/adventure" },
  { title: "Comedy", filter: "/category/comedy" },
  { title: "Crime", filter: "/category/crime" },
  { title: "Drama", filter: "/category/drama" },
  { title: "Family", filter: "/category/family" },
  { title: "Fantasy", filter: "/category/fantasy" },
  { title: "Historical", filter: "/category/historical" },
  { title: "Horror", filter: "/category/horror" },
  { title: "Law", filter: "/category/law" },
  { title: "Life", filter: "/category/life" },
  { title: "Medical", filter: "/category/medical" },
  { title: "Military", filter: "/category/military" },
  { title: "Mystery", filter: "/category/mystery" },
  { title: "Political", filter: "/category/political" },
  { title: "Psychological", filter: "/category/psychological" },
  { title: "Romance", filter: "/category/romance" },
  { title: "School", filter: "/category/school" },
  { title: "Sci-Fi", filter: "/category/sci-fi" },
  { title: "Sports", filter: "/category/sports" },
  { title: "Supernatural", filter: "/category/supernatural" },
  { title: "Thriller", filter: "/category/thriller" },
];
